### ISSUE TITLE
Application Monthly Cost 

### ISSUE THREAD

**Issue by omarhassanhub** [aws-samples/aws-amplify-react-native-events-app-workshop#2]
Hi Team,

Thank you for this great tutorial. I was looking to learn more about the AWS services by creating an event app for my university society. What is the monthly cost of running this app as it is? 

Cheers,
Omar

**Comment by ykbryan** [comment]
Hi Omar,

By the look of the AWS free tier (https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc), it looks like most of the AWS services have free tier in place. It is tough to know the actual costs that will be incurred in the future as most of the services are based on consumption basis. But it is safe to say that it won’t cost a bomb to build and run this for your school because of the AWS free tier in place. U can maybe run a POC to see how much it costs for 1 month before going to production. Hope this helps.

I will be closing this issue.

Thanks.
